FarmLog.Consumes = {
    ["18610"] = {
        name = "First Aid",
        item = "Heavy Runecloth Bandage",
        type = "Consumable",
    },
    ["18608"] = {
        name = "First Aid",
        item = "Runecloth Bandage",
        type = "Consumable",
    },
    ["10839"] = {
        name = "First Aid",
        item = "Heavy Mageweave Bandage",
        type = "Consumable",
    },
    ["10838"] = {
        name = "First Aid",
        item = "Mageweave Bandage",
        type = "Consumable",
    },
    ["7927"] = {
        name = "First Aid",
        item = "Heavy Silk Bandage",
        type = "Consumable",
    },
    ["7926"] = {
        name = "First Aid",
        item = "Silk Bandage",
        type = "Consumable",
    },
    ["3268"] = {
        name = "First Aid",
        item = "Heavy Wool Bandage",
        type = "Consumable",
    },
    ["3267"] = {
        name = "First Aid",
        item = "Wool Bandage",
        type = "Consumable",
    },
    ["1159"] = {
        name = "First Aid",
        item = "Heavy Linen Bandage",
        type = "Consumable",
    },
    ["746"] = {
        name = "First Aid",
        item = "Linen Bandage",
        type = "Consumable",
    },
    ["1090"] = {
        name = "Sleep",
        item = "Magic Dust",
        type = "Consumable",
    },
    ["4064"] = {
        name = "Rough Copper Bomb",
        item = "Rough Copper Bomb",
        type = "Engineering",
    },
    ["4054"] = {
        name = "Rough Dynamite",
        item = "Rough Dynamite",
        type = "Engineering",
    },
    ["4061"] = {
        name = "Coarse Dynamite",
        item = "Coarse Dynamite",
        type = "Engineering",
    },
    ["8331"] = {
        name = "Ez-Thro Dynamite",
        item = "Ez-Thro Dynamite",
        type = "Engineering",
    },
    ["4065"] = {
        name = "Large Copper Bomb",
        item = "Large Copper Bomb",
        type = "Engineering",
    },
    ["4374"] = {
        name = "Small Bronze Bomb",
        item = "Small Bronze Bomb",
        type = "Engineering",
    },
    ["4074"] = {
        name = "Explosive Sheep",
        item = "Explosive Sheep",
        type = "Engineering",
    },
    ["4067"] = {
        name = "Big Bronze Bomb",
        item = "Big Bronze Bomb",
        type = "Engineering",
    },
    ["12419"] = {
        name = "Solid Dynamite",
        item = "Solid Dynamite",
        type = "Engineering",
    },
    ["4062"] = {
        name = "Heavy Dynamite",
        item = "Heavy Dynamite",
        type = "Engineering",
    },
    ["4852"] = {
        name = "Flash Bomb",
        item = "Flash Bomb",
        type = "Engineering",
    },
    ["4100"] = {
        name = "Goblin Land Mine",
        item = "Goblin Land Mine",
        type = "Engineering",
    },
    ["23000"] = {
        name = "Ez-Thro Dynamite",
        item = "Ez-Thro Dynamite",
        type = "Engineering",
    },
    ["13241"] = {
        name = "Goblin Sapper Charge",
        item = "Goblin Sapper Charge",
        type = "Engineering",
    },
    ["10514"] = {
        name = "Mithril Frag Bomb",
        item = "Mithril Frag Bomb",
        type = "Engineering",
    },
    ["4069"] = {
        name = "Big Iron Bomb",
        item = "Big Iron Bomb",
        type = "Engineering",
    },
    ["10586"] = {
        name = "The Big One",
        item = "The Big One",
        type = "Engineering",
    },
    ["23063"] = {
        name = "Dense Dynamite",
        item = "Dense Dynamite",
        type = "Engineering",
    },
    ["12543"] = {
        name = "Hi-Explosive Bomb",
        item = "Hi-Explosive Bomb",
        type = "Engineering",
    },
    ["19769"] = {
        name = "Thorium Grenade",
        item = "Thorium Grenade",
        type = "Engineering",
    },
    ["13808"] = {
        name = "M73 Frag Grenade",
        item = "M73 Frag Grenade",
        type = "Engineering",
    },
    ["19784"] = {
        name = "Dark Iron Bomb",
        item = "Dark Iron Bomb",
        type = "Engineering",
    },
    ["19821"] = {
        name = "Arcane Bomb",
        item = "Arcane Bomb",
        type = "Engineering",
    },
    ["4068"] = {
        name = "Iron Grenade",
        item = "Iron Grenade",
        type = "Engineering",
    },
    ["2094"] = {
        name = "Blind",
        item = "Blinding Powder",
        type = "Poison",
    },
    ["9512"] = {
        name = "Restore Energy",
        item = "Thistle Tea",
        type = "Food",
    },
    ["1856"] = {
        name = "Vanish",
        item = "Flash Powder",
        desc = "Vanish Rank 1",
        type = "Reagent",
    },
    ["1857"] = {
        name = "Vanish",
        item = "Flash Powder",
        desc = "Vanish Rank 2",
        type = "Poison",
    },
    ["25351"] = {
        name = "Deadly Poison V",
        item = "Deadly Poison V",
        type = "Poison",
    },
    ["11356"] = {
        name = "Deadly Poison IV",
        item = "Deadly Poison IV",
        type = "Poison",
    },
    ["11355"] = {
        name = "Deadly Poison III",
        item = "Deadly Poison III",
        type = "Poison",
    },
    ["2824"] = {
        name = "Deadly Poison II",
        item = "Deadly Poison II",
        type = "Poison",
    },
    ["2823"] = {
        name = "Deadly Poison",
        item = "Deadly Poison",
        type = "Poison",
    },
    ["11202"] = {
        name = "Crippling Poison",
        item = "Crippling Poison II",
        type = "Poison",
    },
    ["3408"] = {
        name = "Crippling Poison",
        item = "Crippling Poison",
        type = "Poison",
    },
    ["11399"] = {
        name = "Mind-numbing Poison III",
        item = "Mind-numbing Poison III",
        type = "Poison",
    },
    ["8693"] = {
        name = "Mind-numbing Poison II",
        item = "Mind-numbing Poison II",
        type = "Poison",
    },
    ["5761"] = {
        name = "Mind-numbing Poison",
        item = "Mind-numbing Poison",
        type = "Poison",
    },
    ["11340"] = {
        name = "Instant Poison VI",
        item = "Instant Poison VI",
        type = "Poison",
    },
    ["11339"] = {
        name = "Instant Poison V",
        item = "Instant Poison V",
        type = "Poison",
    },
    ["11338"] = {
        name = "Instant Poison IV",
        item = "Instant Poison IV",
        type = "Poison",
    },
    ["8688"] = {
        name = "Instant Poison III",
        item = "Instant Poison III",
        type = "Poison",
    },
    ["8686"] = {
        name = "Instant Poison II",
        item = "Instant Poison II",
        type = "Poison",
    },
    ["8679"] = {
        name = "Instant Poison",
        item = "Instant Poison",
        type = "Poison",
    },
    ["15701"] = {
        name = "Night Dragon's Breath",
        item = "Night Dragon's Breath",
        type = "BoP Consumable",
    },
    ["16666"] = {
        name = "Demonic Rune",
        item = "Demonic Rune",
        type = "BoP Consumable",
    },
    ["15700"] = {
        name = "Whipper Root Tuber",
        item = "Whipper Root Tuber",
        type = "BoP Consumable",
    },
    ["26677"] = {
        name = "Cure Poison",
        item = "Elixir of Poison Resistance",
        type = "Consumable",
    },
    ["17550"] = {
        name = "Purification",
        item = "Purification Potion",
        type = "Consumable",
    },
    ["2379"] = {
        name = "Speed",
        item = "Swiftness Potion",
        type = "Consumable",
    },
    ["24364"] = {
        name = "Living Free Action",
        item = "Living Action Potion",
        type = "Consumable",
    },
    ["23786"] = {
        name = "Powerful Anti-Venom",
        item = "Powerful Anti-Venom",
        type = "Consumable",
    },
    ["7933"] = {
        name = "Strong Anti-Venom",
        item = "Strong Anti-Venom",
        type = "Consumable",
    },
    ["7932"] = {
        name = "Anti-Venom",
        item = "Anti-Venom",
        type = "Consumable",
    },
    ["3169"] = {
        name = "Invulnerability",
        item = "Limited Invulnerability Potion",
        type = "Consumable",
    },
    ["6615"] = {
        name = "Free Action",
        item = "Free Action Potion",
        type = "Consumable",
    },
    ["17531"] = {
        name = "Restore Mana",
        item = "Major Mana Potion",
        type = "Consumable",
    },
    ["17530"] = {
        name = "Restore Mana",
        item = "Superior Mana Potion",
        type = "Consumable",
    },
    ["6149"] = {
        name = "Restore Mana",
        item = "Greater Mana Potion",
        type = "Consumable",
    },
    ["17534"] = {
        name = "Healing Potion",
        item = "Major Healing Potion",
        type = "Consumable",
    },
    ["4042"] = {
        name = "Healing Potion",
        item = "Superior Healing Potion",
        type = "Consumable",
    },
    ["2024"] = {
        name = "Healing Potion",
        item = "Greater Healing Potion",
        type = "Consumable",
    },
    ["3593"] = {
        name = "Health II",
        item = "Elixir of Fortitude",
        type = "Consumable",
    },
    ["3222"] = {
        name = "Regeneration (6 hp5)",
        item = "Strong Troll's Blood Potion",
        type = "Consumable",
     },
     ["3223"] = {
        name = "Regeneration (12 hp5)",
        item = "Mighty Troll's Blood Potion",
        type = "Consumable",
     },
     ["24361"] = {
        name = "Regeneration (20 hp5)",
        item = "Major Troll's Blood Potion",
        type = "Consumable",
     },
     ["24363"] = {
        name = "Mana Regeneration (12 mp5)",
        item = "Mageblood Potion",
        type = "Consumable",
     },
     ["17549"] = {
        name = "Greater Arcane Protection",
        item = "Greater Arcane Protection Potion",
        type = "Consumable",
    },
    ["17543"] = {
        name = "Greater Fire Protection",
        item = "Greater Fire Protection Potion",
        type = "Consumable",
    },
    ["7233"] = {
        name = "Fire Protection",
        item = "Fire Protection Potion",
        type = "Consumable",
    },
    ["17548"] = {
        name = "Greater Shadow Protection",
        item = "Greater Shadow Protection Potion",
        type = "Consumable",
    },
    ["7242"] = {
        name = "Shadow Protection",
        item = "Shadow Protection Potion",
        type = "Consumable",
    },
    ["17546"] = {
        name = "Greater Nature Protection",
        item = "Greater Nature Protection Potion",
        type = "Consumable",
    },
    ["7254"] = {
        name = "Nature Protection",
        item = "Nature Protection Potion",
        type = "Consumable",
    },
    ["17544"] = {
        name = "Greater Frost Protection",
        item = "Greater Frost Protection Potion",
        type = "Consumable",
    },
    ["7239"] = {
        name = "Frost Protection",
        item = "Frost Protection Potion",
        type = "Consumable",
    },
    ["17539"] = {
        name = "Greater Arcane Elixir",
        item = "Greater Arcane Elixir",
        type = "Consumable",
    },
    ["11474"] = {
        name = "Elixir of Shadow Power",
        item = "Elixir of Shadow Power",
        type = "Consumable",
    },
    ["17538"] = {
        name = "Elixir of the Mongoose",
        item = "Elixir of the Mongoose",
        type = "Consumable",
    },
    ["11405"] = {
        name = "Elixir of the Giants",
        item = "Elixir of the Giants",
        type = "Consumable",
    },
    ["16326"] = {
        name = "Juju Ember",
        item = "Juju Ember",
        desc = "Fire Res Juju",
        type = "Consumable",
    },
    ["16329"] = {
        name = "Juju Might",
        item = "Juju Might",
        desc = "Attack Power Juju",
        type = "Consumable",
    },
    ["16323"] = {
        name = "Juju Power",
        item = "Juju Power",
        desc = "Strength Juju",
        type = "Consumable",
    },
    ["16322"] = {
        name = "Juju Flurry",
        item = "Juju Flurry",
        desc = "Attack Speed Juju",
        type = "Consumable",
    },
    ["16325"] = {
        name = "Juju Chill",
        item = "Juju Chill",
        desc = "Frost Res Juju",
        type = "Consumable",
    },
    ["16321"] = {
        name = "Juju Escape",
        item = "Juju Escape",
        desc = "Dodge Juju",
        type = "Consumable",
    },
    ["17628"] = {
        name = "Supreme Power",
        item = "Flask of Supreme Power",
        type = "Flask",
    },
    ["17626"] = {
        name = "Flask of the Titans",
        item = "Flask of the Titans",
        type = "Flask",
    },
    ["17627"] = {
        name = "Distilled Wisdom",
        item = "Flask of Distilled Wisdom",
        type = "Flask",
    },
    ["24870"] = {
        name = "Well Fed (?? sta, ?? spi)",
        type = "Food",
    },
    ["19705"] = {
        name = "Well Fed (1 sta, 1 spi)",
        type = "Food",
    },
    ["19706"] = {
        name = "Well Fed (3 sta, 3 spi)",
        type = "Food",
    },
    ["19709"] = {
        name = "Well Fed (7 sta, 7 spi)",
        type = "Food",
    },
    ["19710"] = {
        name = "Well Fed (11 sta, 11 spi)",
        type = "Food",
    },
    ["19711"] = {
        name = "Well Fed (13 sta, 13 spi)",
        type = "Food",
    },
    ["25694"] = {
        name = "Well Fed",
        desc = "Well Fed (2 mp5)",
        item = "Brain Food",
        type = "Food",
    },
    ["25941"] = {
        name = "Well Fed",
        desc = "Well Fed (5 mp5)",
        item = "Brain Food",
        type = "Food",
    },
    ["18194"] = {
        name = "Mana Regeneration",
        name = "Well Fed (7 mp5)",
        item = "Nightfin Soup",
        type = "Food",
    },
    ["22730"] = {
        name = "Increased Intellect",
        name = "Well Fed (9 int)",
        item = "Runn Tum Tuber Surprise",
        type = "Food",
    },
    ["18192"] = {
        name = "Increased Agility",
        desc = "Well Fed (9 agi)",
        item = "Grilled Squid",
        type = "Food",
    },
    ["24799"] = {
        name = "Well Fed",
        desc = "Well Fed (19 str)",
        item = "Smoked Desert Dumpling",
        type = "Food",
    },
    ["22789"] = {
        name = "Gordok Green Grog",
        item = "Gordok Green Grog",
        desc = "Well Fed (10 sta)",
        type = "Alcohol",
    },
    ["22790"] = {
        name = "Kreeg's Stout Beatdown",
        item = "Kreeg's Stout Beatdown",
        desc = "Well Fed (25 spi, -5 int)",
        type = "Alcohol",
    },
    ["25804"] = {
        name = "Rumsey Rum Black Label",
        item = "Rumsey Rum Black Label",
        desc = "Well Fed (15 sta)",
        type = "Alcohol",
    },
    ["24870"] = {
        name = "Well Fed",
        item = "Winter Veil Cookie",
        desc = "Well Fed (15 sta, 15 spi)",
        type = "Food",
    },
    ["18125"] = {
        name = "Blessed Sunfruit",
        item = "Blessed Sunfruit",
        desc = "Well Fed (10 str)",
        type = "Food",
    },
    ["8090"] = {
        name = "Bright Baubles",
        item = "Bright Baubles",
        desc = "Fishing Lure +75",
        type = "Consumable",
    },
    ["8089"] = {
        name = "Aquadynamic Fish Attractor",
        item = "Aquadynamic Fish Attractor",
        desc = "Fishing Lure +100",
        type = "Consumable",
    },
    ["8088"] = {
        name = "Nightcrawlers",
        item = "Nightcrawlers",
        desc = "Fishing Lure +50",
        type = "Consumable",
    },
    ["8087"] = {
        name = "Shiny Bauble",
        item = "Shiny Bauble",
        desc = "Fishing Lure +25",
        type = "Consumable",
    },
    ["8532"] = {
        name = "Aquadynamic Fish Lens",
        item = "Aquadynamic Fish Lens",
        desc = "Fishing Lure +50",
        type = "Consumable",
    },
    ["7307"] = {
        name = "Flesh Eating Worm",
        item = "Flesh Eating Worm",
        desc = "Fishing Lure +75",
        type = "Consumable",
    },
}
